### ISSUE TITLE
Output is always grayscale, regardless of input

### ISSUE THREAD

**Issue by sarthakpati** [CBICA/HistoReg#15] opened 2020-09-03 17:16 UTC
The output of HistoReg is always grayscale, even if the input is color. This needs to be corrected to ensure that the output matches the input image color space.

Reported by @grenkoca

**Comment by sarthakpati** [comment] 2020-09-03 17:28
The more I think about it, the more I realize this requires some major development. Here are my main points of thought:

- The registrations is **always** done on NIfTI images, regardless of input
- The most naive way to do this is to get the transformation as we are getting right now but instead of applying it to the converted NIfTI, we split the input into its respective R,G and B channels and apply it.
  - NIfTI conversion does a channel-level compression
  - Not ideal registration as we would probably want to do individual registrations of `R(moving) -> R(target)`, and similar for G and B

We should probably have a chat with Paul if Greedy can take an image with a vector pixel as input. Tagging @sbakas

**Comment by grenkoca** [comment] 2020-09-03 20:04
>     Not ideal registration as we would probably want to do individual registrations of R(moving) -> R(target), and similar for G and B

What if we converted to grayscale (as it is now), and then used that to find one diffeomorphic mapping function. From there, we apply the function to all three channels of the RGB image. Wouldn't that result in a transformed RGB image?

**Comment by sarthakpati** [comment] 2020-09-03 20:15
> > ```
> > Not ideal registration as we would probably want to do individual registrations of R(moving) -> R(target), and similar for G and B
> > ```
> 
> What if we converted to grayscale (as it is now), and then used that to find one diffeomorphic mapping function. From there, we apply the function to all three channels of the RGB image. Wouldn't that result in a transformed RGB image?

This is the naive approach I mentioned, but since we do not have control over how the grayscale conversion is happening (I think it might be equally weighted, right now), the results would probably not be optimal... Anyway, can always give this a go and see how the results look...

**Comment by ludovenet** [comment] 2020-09-04 10:14
> The output of HistoReg is always grayscale, even if the input is color. This needs to be corrected to ensure that the output matches the input image color space.
> 
> Reported by @grenkoca

Have you tried to apply the registration on full resolution images with the "-F" option? This option will apply the transformation calculated with the reduced resolution and grayscale images to the original RGB images. So the output should be RGB in full resolution.
On the other hand, the "-S" option applies the transformation to the reduced resolution and grayscale images.  The calculation is thus much faster and allows to check if the registration seems to be correct or not.

**Comment by grenkoca** [comment] 2020-09-09 16:07
> Have you tried to apply the registration on full resolution images with the "-F" option? 

Yep :/ 

It runs through the motions of applying the transformations to the original RGB image, but the output is still gray. I'm trying to trace through the program which is proving a lot harder than I thought because I need to brush up on my c++. Do you have a repo where this is confirmed working that I can look back to?

**Comment by ludovenet** [comment] 2020-09-16 14:51
Hi @grenkoca, with the help of @sarthakpati we have resolved the issue and updated the code.
If you pull the changes and try again the output should be RGB.

Thanks for the review, I am closing the issue, please re-open if necessary.

**Closed by ludovenet** 2020-09-16 14:51 UTC
